### ISSUE TITLE
lua utf8 library is a lua5.3+ feature

### ISSUE THREAD

**Issue by rnpnr** [orbitalquark/scintillua#103]
Hi,

In the README you say that only lua5.1 is required for using scintillua
as a standalone library but the utf8 library, in use since (possibly)
3f7febe, is lua5.3+ only. Was this an intentional change?

**Comment by orbitalquark** [comment]
It was an accident. Thanks for catching this. Fixed via https://github.com/orbitalquark/scintillua/commit/50485b521d85432092492ce74d8d5feeddf5ac4a
