### ISSUE TITLE
Syncing changes in ansi_c lexer

### ISSUE THREAD

**Issue by moesasji** [orbitalquark/scintillua#21]
As you had probably guessed: I'm trying to sync the lexers used by vis so that both communities can benefit from each-others effort.

Unfortunately adding [this commit](https://github.com/martanne/vis/commit/1e9eb86abc67aaec02475ef45b8dc3a121b53e36#diff-1f31980b54e8f9f5a2d5a72982205d09cb06fe528917937658bc1e61a0b99720) on top of the current ansi_c lexer is a bit less straight forward due to the range of things it changed on top of the legacy lexer. 

Key changes are in how it recognises the numbers as well adding additional non-std compiler keywords. Any change that you could take a look at how to best merge this one without me preparing a pull-request?

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/scintillua/commit/6678d3f9bf33ef00f66848a5252a8f93c21896d2
