### ISSUE TITLE
use of deprecated function in the jq lexer

### ISSUE THREAD

**Issue by moesasji** [orbitalquark/scintillua#23]
The jq lexer triggers a warning that it uses a deprecated function, which is [caused by this line](https://github.com/orbitalquark/scintillua/blob/default/lexers/jq.lua#L13)

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/scintillua/commit/5b90f44495fd785a3d32091c91c4d11ae3c87bed
