### ISSUE TITLE
Syncing changes in the scheme lexer

### ISSUE THREAD

**Issue by moesasji** [orbitalquark/scintillua#24]
The scheme lexer in vis currently has a [pretty extensive patch](https://github.com/martanne/vis/commit/64554981c786c7a95e64c9f4336d3624d7239672) on top of the legacy lexer. Although it is clearly an improvement I don't feel confident enough to merge this on top of the current lexer. Any chance you could take a look at how much is actually relevant?

Thanks in advance.

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/scintillua/commit/b4efb1173162e04ffc3bf8e602a2a70156b41845
