### ISSUE TITLE
Correctly formatting nesting variables in bash lexer

### ISSUE THREAD

**Issue by moesasji** [orbitalquark/scintillua#25]
Vis currently caries the following [patch](https://github.com/martanne/vis/commit/21727ae3dce8ccea2e342d3b62b5fa67b1b5a936#diff-77caf695dadebc3270093253f1827e75126e21ad828717f313fba832fa194242) to correctly format nested strings in bash like the following test case:

`
${FOO:="${bar}/baz"}
`

Currently the bash lexer in scintillua will format the last '"}' wrong, so that bug is still present. The fix in vis added the balanced flag to the delimiter_range function, but adding that same flag to the range function that replaces it doesn't work.

I suspect something is missing in the [range()](https://github.com/orbitalquark/scintillua/blob/default/lexers/lexer.lua#L1736) function if I compare it to the same part in [delimited_range?](https://github.com/orbitalquark/scintillua/blob/default/lexers/lexer.lua#L1781)

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/scintillua/commit/383e98d9d1dc4649ec580e7853beec8afdf23796
