### ISSUE TITLE
lexers compatible with scintillua

### ISSUE THREAD

**Issue by brynne8** [orbitalquark/scintillua#36]
You might be interested in lexers defined at [leafo/lua-syntaxhighlight](https://github.com/leafo/lua-syntaxhighlight/tree/master/syntaxhighlight/lexers), especially the nginx lexer, for ngx_lua / OpenResty development.

**Comment by orbitalquark** [comment]
Thanks, I'll take a look.

**Comment by orbitalquark** [comment]
I have incorporated some fixes to Moonscript[1]. I did not add any new lexers as they appear to be incomplete or a work-in-progress. I generally prefer lexers to be submitted by the authors themselves.

[1]: https://github.com/orbitalquark/scintillua/commit/8b37dd333f7fcccb86fd8776a6dccae81e4f5805
