### ISSUE TITLE
Can't disable Lua lexer through properties

### ISSUE THREAD

**Issue by ittegrat** [orbitalquark/scintillua#54]
With Scintillua installed in SciTE (Sc1, single file), I can't disable a Lua lexer resetting the property `lexer.$(file.patterns.name)=name` to the original lexilla lexer.
It seems to me that a recent commit in lexilla https://github.com/ScintillaOrg/lexilla/commit/e4817a112aca6fbf51a513d5d477c6eea7000b63 breaks the Scintillua behavior and a default Lua lexer is always created and set after been called by [Lexilla::MakeLexer](https://github.com/ScintillaOrg/lexilla/blob/3e64a1881a67e6acc81cfece71e0bbc8eb9bb3b1/access/LexillaAccess.cxx#L238).
Any suggestions on how to get around this ?

**Comment by orbitalquark** [comment]
I cannot think of a way to get around this other than removing or renaming *lexers/lua.lua*.

**Comment by orbitalquark** [comment]
I'm going to close this because it's a special case of using the statically linked version of SciTE that does not have lexer namespacing. This is ultimately a SciTE/Lexilla issue, not a Scintillua issue because it simply uses the tools Lexilla provides.
