### ISSUE TITLE
Merge vis lexers

### ISSUE THREAD

**Issue by Nomarian** [orbitalquark/scintillua#68]
Missing lexers from vis should be migrated here instead.

- dsv
- gemini
- git-rebase
- strace
- vbscript

**Comment by orbitalquark** [comment]
I chose not to include the first four lexers originally submitted here: https://github.com/orbitalquark/scintillua/pull/13

vbscript is identical to vb and is no longer needed separately: https://github.com/orbitalquark/scintillua/commit/dee7d765a0057eca938412d63b3e95742d7a5a65

**Comment by orbitalquark** [comment]
I chose not to include the first four lexers originally submitted here: https://github.com/orbitalquark/scintillua/pull/13

vbscript is identical to vb and is no longer needed separately: https://github.com/orbitalquark/scintillua/commit/dee7d765a0057eca938412d63b3e95742d7a5a65
