### ISSUE TITLE
Nix lexer

### ISSUE THREAD

**Issue by sikmir** [orbitalquark/scintillua#75]
Would be great to have Nix lexer. As NixOS and vis user I really miss it.
See https://github.com/martanne/vis/issues/880

**Comment by orbitalquark** [comment]
Thanks for the suggestion!

**Comment by orbitalquark** [comment]
Thanks for the suggestion!

**Comment by samuelmarquis** [comment]
I'm on it

**Comment by orbitalquark** [comment]
This is done thanks to @samuelmarquis in #122. Thank you!
