### ISSUE TITLE
latest SciTE v5.3.0 not working with scintillua 5.3 (Windows)

### ISSUE THREAD

**Issue by rlatowicz** [orbitalquark/scintillua#78]
Hi,

Thanks for Scintillua!

SciTE v5.3.0 seems to have broken something?

**SciTE v5.2.4 & Scintillua v5.3** worked together perfectly.

before,
![2022-09-19 01_13_30-D__Coding_Work_Bezier_C_vec2d_005 h - SciTE](https://user-images.githubusercontent.com/12681122/190914438-7cae23c8-78a6-4ad5-b308-9eaaae31573c.png)

after (simply updating **SciTE.exe, Scintilla.dll & Lexilla.dll**),
![2022-09-19 01_15_37-D__Coding_Work_Bezier_C_vec2d_005 h - SciTE](https://user-images.githubusercontent.com/12681122/190914452-840f9ae0-02f7-4e35-8fbd-d16a2dfb8f93.png)

I'm using SciTE 64bit on Windows 8.1.

best regards,
Rafael.

**Comment by orbitalquark** [comment]
Scintillua is currently in a transition period. I submitted some changes for SciTE 5.3.0 that are incompatible with Scintillua 5.x. When Scintillua 6.0 is released, which I hope will be soon, it will work with SciTE 5.3.0. Sorry for the inconvience :(

**Comment by rlatowicz** [comment]
@orbitalquark 

Thanks for the update.
That's great news.

Thanks again for the awesome work on Scintillua.

All the best,
Rafael.

**Comment by orbitalquark** [comment]
Scintillua 6.0 has been released and should work with SciTE. Please see the updated [manual][] with instructions how to use the new version. It is quite different from the previous version, such as when it comes to themes. (Lua themes have been replaced by SciTE-style properties files.)

[manual]: https://orbitalquark.github.io/scintillua/manual.html#using-scintillua-with-scite
