### ISSUE TITLE
lexer.number_ ???

### ISSUE THREAD

**Issue by mcepl** [orbitalquark/scintillua#88]
https://github.com/orbitalquark/scintillua/blob/2181945f83beef745044ad6ab05f41395485ea3a/lexers/ada.lua#L42

Are you certain `lexer.number_()` (notice the underscore) is correct? Shouldn’t it be without it?

**Comment by orbitalquark** [comment]
Ada appears to allow '_' in numbers, so that's correct. 
https://github.com/orbitalquark/scintillua/commit/40dccafaa489435f3dfd22333e3eb93796873733#diff-04e98e87b78fe7a29d3f44e1eaee737a6ce947a915798c9594986c674afb2654

**Comment by mcepl** [comment]
I meant the first underscore (`number_` instead of `number`). And yes, it is there as well. OK, I will have to bait the bullet and try to debug `lexer.lua` as well. Oh well.

**Comment by orbitalquark** [comment]
No, `number_` is correct. It's a new feature.
